### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Gabriel-p** [Deech08/whampy#2] opened 2019-12-09 13:18 UTC
Hi there, I'm one of the reviewers of your package for JOSS (see: https://github.com/openjournals/joss-reviews/issues/1940)

The example in the README includes loading a survey with:

```
>>> from whampy.skySurvey import SkySurvey
>>> # Load the Survey
>>> survey = SkySurvey()
```

but this fails with:

    FileNotFoundError: [Errno 2] No such file or directory: '/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/whampy/data/wham-ss-DR1-v161116-170912.fits'

Is this file supposed to come with the installed package or is must the user download it from somewhere else?

**Comment by Deech08** [comment] 2019-12-09 16:43
Uh oh - if the file isn't found its "supposed" to download it from a url. I will check what's happening!

**Comment by Deech08** [comment] 2019-12-09 20:01
This should now be resolved in the latest version on github and the latest pip installable version  (v0.1.0a7). It will now auto download the survey data into the default directory (within the package) on first load of the survey.

**Comment by Deech08** [comment] 2019-12-09 20:11
Just as a heads up - the TravisCI build is currently failing because a server is down associated with the dustmaps package - an optional dependency. I will restart the build when I notice it is up and running again!

**Closed** 2019-12-12 16:49 UTC

**Comment by HeloiseS** [comment] 2019-12-12 17:33
> Just as a heads up - the TravisCI build is currently failing because a server is down associated with the dustmaps package - an optional dependency. I will restart the build when I notice it is up and running again!

Travis is very slow sometimes :) As for me I'll only check your travis build at the end once both me and @Gabriel-p have checked everything we wanted to check and once you've had the ability to close our issues - so no worries

**Comment by Gabriel-p** [comment] 2019-12-12 18:06
Upgraded to `v0.1.0a7`, now it attempts to download the file but after a while fails with:

```
>>> survey = SkySurvey()
Downloading survey to /home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/whampy/data/wham-ss-DR1-v161116-170912.fits
Traceback (most recent call last):
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/whampy/skySurvey.py", line 188, in __init__
    f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/whampy/data/wham-ss-DR1-v161116-170912.fits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/whampy/skySurvey.py", line 193, in __init__
    urllib.request.urlretrieve(url, filename)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```



You should consider using a smaller file or adding it to the package.

**Comment by HeloiseS** [comment] 2019-12-12 18:09
I had the same problem and then the following issue [occured](https://github.com/Deech08/whampy/issues/3)

It would be worth warning the user that this is a big file and will take a while to download if it's not added to the package.

**Comment by Deech08** [comment] 2019-12-12 18:41
I was originally planning to fix this with a file check / redownload but I think I will just try and include it in the package instead. I believe I’ll need to request a file size limit increase on PyPi so I will update both issues when it’s done!

Thanks for catching these errors - I haven’t necessarily been able to reproduce them but I think I can if I interrupt the download.

**Comment by Deech08** [comment] 2019-12-12 19:57
Latest version (v0.2.0a1) is now pip installable and updated on the repo. This release includes the survey data in the package itself and no additional download is necessary. So as long as the package installs it should be good to go.
